FROM bioconductor/bioconductor_docker:RELEASE_3_14

RUN apt-get update && \
        apt-get install -y --no-install-recommends libhiredis-dev && \
        rm -rf /var/lib/apt/lists/*

RUN R -e 'BiocManager::install("Bioconductor/BiocKubeInstall")'

COPY worker.R /home/docker/
