FROM bioconductor/bioconductor_docker:devel

RUN apt-get update && \
	apt-get install -y --no-install-recommends libhiredis-dev vim && \
	rm -rf /var/lib/apt/lists/*

RUN R -e 'BiocManager::install("Bioconductor/BiocKubeInstall", ref = "local")'
RUN R -e 'BiocManager::install("Bioconductor/BiocParallel")'

COPY manager_demo.R /home/rstudio/manager_demo.R
COPY 01-Renviron /etc/cont-init.d/01-Renviron
