FROM bioconductor/bioconductor_docker:RELEASE_3_13

## Install Redis and vim
# Add the Google Cloud SDK distribution URI as a package source
# Import the Google Cloud public key
# Update the package list and install the Cloud SDK
RUN apt-get update && apt-get install -yq --no-install-recommends \
    gnupg \
    lsb-release \
 && echo "deb http://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list \
 && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - \
 && apt-get update \
 && apt-get install -yq --no-install-recommends \
    google-cloud-sdk \
    libhiredis-dev \
    vim \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

## Install azure CLI and azcopy / download and cleanup
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash \
    && wget -O /tmp/azcopy.tar.gz  https://aka.ms/downloadazcopy-v10-linux \
    && tar -xf /tmp/azcopy.tar.gz -C /tmp/ \
    && mv /tmp/azcopy_linux_amd64*/azcopy /usr/local/bin \
    && rm -rf /tmp/azcopy.tar.gz /tmp/azcopy_linux_amd64*

RUN R -e 'BiocManager::install("Bioconductor/BiocKubeInstall")'

ENV BIOC_REDIS_JOB_NAME=biocredis

COPY manager_demo.R /home/rstudio/manager_demo.R
COPY worker.R /home/docker/
COPY 01-Renviron /etc/cont-init.d/01-Renviron
