FROM bioconductor/bioconductor_docker:devel

RUN apt-get update && \
        apt-get install -y --no-install-recommends libhiredis-dev && \
        rm -rf /var/lib/apt/lists/*

RUN R -e 'BiocManager::install("Bioconductor/BiocKubeInstall")'
RUN R -e 'BiocManager::install("Bioconductor/BiocParallel")'

COPY worker.R /home/docker/
