apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-provisioning-demo
  labels:
    demo: nfs-pvc-provisioning
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
---
{{ if (or .Values.persistence.gcpPdName .Values.persistence.azurePdHandle) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Release.Namespace}}-nfs-pv-provisioning-demo
  labels:
    demo: nfs-pv-provisioning
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes: [ "ReadWriteOnce" ]
  capacity:
    storage: {{ .Values.persistence.size }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: nfs-pvc-provisioning-demo
  {{- include "biockubeinstall.manualDiskBlock" . | nindent 2 }}
---
{{ end }}