name: devel - Delete k8s cluster

## Cluster is shut down at 6pm UTC on Monday, Wed, Fri
## The k8s cluster has 6 hours to do the job
on: 
  schedule:
    - cron:  '30 22 * * 2'
  workflow_dispatch:
    inputs:
      name: 
        description: 'Stop cluster'
        required: false
        default: 'biock8sredis'
        
env:
  GKE_CLUSTER: biock8sredis
  GKE_ZONE: us-east1-b
  DEPLOYMENT_NAME: binaryBuilder

jobs:
  setup-start-deploy:
    name: Delete GKE cluster
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Install helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    # Get the GKE credentials so we can delete chart in the cluster
    - run: |-
       gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Although deleting the cluster is enough for deleting all k8s resources,
    # deleting the chart is needed for handling the cleanup process of some resources
    # (eg: having the GCP storage class delete the persistent disk when the PVC is deleted)
    - name: Delete chart
      run: |
        helm delete biock8sredis

    # Delete cluster
    - run: |-
        gcloud container clusters delete "$GKE_CLUSTER" --zone "$GKE_ZONE" --quiet

    # Delete pd
    - run: |-
        gcloud compute disks delete --zone "$GKE_ZONE" --quiet $(gcloud compute disks list --format="value(name)" --filter='status~READY' --filter='name~biockubeinstall-nfs-pd-*')
